-- MySQL Script generated by MySQL Workbench
-- Tue May 30 17:01:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_PHP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_PHP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_PHP` DEFAULT CHARACTER SET utf8 ;
USE `mydb_PHP` ;

-- -----------------------------------------------------
-- Table `mydb_PHP`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_PHP`.`Estudiante` (
  `idEstudiante` INT NOT NULL,
  `nombreE` VARCHAR(60) NULL,
  `apellidoE` VARCHAR(60) NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_PHP`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_PHP`.`Materia` (
  `idMateria` INT NOT NULL,
  `nombreM` VARCHAR(45) NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_PHP`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_PHP`.`Curso` (
  `Estudiante_idEstudiante` INT NOT NULL,
  `Materia_idMateria` INT NOT NULL,
  INDEX `fk_Curso_Estudiante_idx` (`Estudiante_idEstudiante` ASC) VISIBLE,
  INDEX `fk_Curso_Materia1_idx` (`Materia_idMateria` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Estudiante`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `mydb_PHP`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb_PHP`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
